### ISSUE TITLE
Check FIN/LEG imports in the legal/finance.py files

### ISSUE THREAD

**Issue by mehmetbutgul** [JohnSnowLabs/johnsnowlabs#333]
![NerQA](https://github.com/JohnSnowLabs/johnsnowlabs/assets/109360261/16f92924-3022-422b-bb71-1b0becbb9112)

FIN/LEG annotators which extend healthcare annotators in the spark-nlp-internal should use correct imports. 
If the FIN/LEG annotators call healthcare classes, this situation results in scope problems.
Especially NerQA

**Comment by C-K-Loan** [comment]
Thanks @mehmetbutgul  this is resolved in 447 release
