### ISSUE TITLE
Add Chunk2Token class to Johnsnowlabs

### ISSUE THREAD

**Issue by mehmetbutgul** [JohnSnowLabs/johnsnowlabs#348]
Add Chunk2Token class import to medical,legal, finance.py
see https://github.com/JohnSnowLabs/spark-nlp-internal/pull/1914 
also seehttps://github.com/JohnSnowLabs/spark-nlp-internal/pull/1914#issuecomment-1577452793

**Comment by C-K-Loan** [comment]
`Doc2ChunkInternal` and `AverageEmbeddings` added to legal/finance/medical in 447 release thanks @Cabir40

**Comment by Cabir40** [comment]
@C-K-Loan , We missed the add `Chunk2Token`  to the `johnsnowlabs.medical`

**Comment by Mary-Sci** [comment]
@C-K-Loan 

I tried to run this step

![image](https://github.com/JohnSnowLabs/johnsnowlabs/assets/67653613/d4e23f31-280d-4c5f-a882-29d6884c4cc9)

I got this

![image](https://github.com/JohnSnowLabs/johnsnowlabs/assets/67653613/57544a3f-6f53-42ec-8846-d0908ce38e2e)

Do you have any suggestions?

**Comment by Cabir40** [comment]
now we have a new annotator `ExtractiveSummarization`, we can add all libs medical, finance, and legal

**Comment by C-K-Loan** [comment]
@Cabir40   `ExtractiveSummarization` ,`Chunk2Token` , `ChunkFiltererApproach` are in 4.4.10

@Mary-Sci  I think you mean `visual.VisualDocumentNERv2` which now is available

**Comment by C-K-Loan** [comment]
all issues were resolved in 4.4.10 closing
