### ISSUE TITLE
Add DocumentFiltererByClassifier annotator to johnsnowlabs

### ISSUE THREAD

**Issue by mehmetbutgul** [JohnSnowLabs/johnsnowlabs#798]
When supporting spark-nlp-jsl==5.2.0, add  `DocumentFiltererByClassifier` to johnsnowlabs

**Comment by Cabir40** [comment]
@C-K-Loan 
Can we update the ZeroShotNerModel  import
Currently `medical.ZeroShotNerModel` using an opensource annotator, 
we need to update it with  `sparknlp_jsl.annotator.ner.zero_shot_ner.ZeroShotNerModel`

**Comment by Cabir40** [comment]
@C-K-Loan  in 5.2.0, we have a new `DocumentFiltererByClassifier` annotator for medical finance and legal

**Comment by Cabir40** [comment]
@C-K-Loan @mehmetbutgul , could you add it to next release pelase
