### ISSUE TITLE
Old naming in output

### ISSUE THREAD

**Issue by josejuanmartinez** [JohnSnowLabs/johnsnowlabs#8]
Hey, buggito. In the output it says `jsl.install(secrets_file=...)`

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/36634572/196487921-6d1b09d4-1ff6-4a4a-99bc-adf73cc35fc1.png">

<img width="885" alt="image" src="https://user-images.githubusercontent.com/36634572/196488023-f3b750c6-21bc-480f-92c5-8555cfd7606c.png">

while it should say...

`json_license_path`

**Comment by C-K-Loan** [comment]
Will be fixed in next release

**Comment by KshitizGIT** [comment]
It also says `jsl.install` instead of the new `nlp.install` in outputs
![jsl](https://user-images.githubusercontent.com/8330582/206425861-fea67609-e9c5-4c09-a78c-3834bac7e57a.jpg)

**Comment by C-K-Loan** [comment]
fixed in 4.2.8 release
